version: "3"
services:

  # Redis
  redis:
    build: docker/redis
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    expose:
      - 6379
    ports:
      - 6379:6379

  # Redis-LRU
  redis-lru:
    build: docker/redis
    volumes:
      - ./docker/redis/redis-lru.conf:/usr/local/etc/redis/redis.conf
    expose:
      - 6379
    ports:
      - 6380:6379

  # API
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    volumes:
      - ./config/api.json:/app/api.json
    expose:
      - 3400
    ports:
      - 3400:3400/udp
    links:
      - redis
      - redis-lru
